### PR TITLE
Add support for esp32

### PR DESCRIPTION
**Pull request by taks**

### CODE REVIEW

**Comment by persello** [comment]
Hello, thanks for your contribution. I just published v0.2.0, in which I add notification and indication support. I’ll try to integrate your changes soon, but on the latest release of the library.

**Comment by persello** [comment]
Can’t test on a standard ESP32, please let me know if you can test the checkboxed features with some client such as LightBlue. If it works, I’m ready to merge.

**Review by persello — APPROVED** [review]

**Comment by taks** [comment]
Thank you for merging.
I'm testing the example/server code on ESP32.
Read and Write of Characteristics are working correctly.
However, when I send a Notify registration request from another device, the following error occurs.
```
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: EspError(4364)', C:\Users\1\.cargo\git\checkouts\bluedroid-f79b171abed71d3a\46394d6\src\gatt_server\custom_attributes.rs:61:66
```

I'm investigating that cause now.

**Comment by persello** [comment]
Check that you have an NVS partition, because the CCCD needs it. In the latest commits on the develop branch, I added a few error messages that might help to diagnose this.

**Comment by taks** [comment]
Thank you for your advice.
The NVS partition exists.

When I set the Log level to Debug and executed it, the following log was displayed.
```
D (10279) bluedroid::gatt_server::custom_attributes: Write CCCD value: [1, 0] at key DD404531-006C
```
The length of the stored value is 2.
However, since the length of buf on the read side is 1, this error occurs.
https://github.com/pulse-loop/bluedroid/blob/a79bb5d165eddd6fb7e29cf46f05610fc4acbed6/src/gatt_server/custom_attributes.rs#L79

When I changed the length of buf to 2, the program worked.
Is it correct that the length of buf is 2?

**Comment by persello** [comment]
I can't find any official documentation that states the actual length of the CCCD, but it seems to be 16 bits. Which is quite strange, since only the last 2 bits are used. I'll investigate further, but if setting the length to 2 fixes that for you, we can change it and merge.

**Comment by persello** [comment]
Many sources show that the CCCD’s value is 2 bytes long. Since you confirm that changing the buffer length to 2 works, I’ll make this edit and merge this PR.

**Comment by persello** [comment]
I’m changing the base branch for this PR to `develop`, since `master` is meant for releases.

**Comment by persello** [comment]
Please check on the `develop` branch if the example works for you.
I had some issues merging because of the base branch change, and I also integrated some changes requested on issue #2. I can successfully compile and run the example on my ESP32-C3 with the 2022-10-30 nightly compiler.
If it works, I’m going to release v0.3.1 on crates.io.

**Comment by taks** [comment]
Thank you.
I tested on the `develop` branch with ESP32 and it worked fine.

**Pull request merged**
